name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:     
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git unzip openjdk-17-jdk python3-pip \
            libtool-bin autoconf automake \
            pkg-config zlib1g-dev libncurses5-dev \
            libffi-dev libssl-dev gettext \
            libltdl7 python3-dev liblzma-dev \
            uuid-dev libc-dev

      - name: Install Buildozer with specific versions
        run: |
          pip install --upgrade pip wheel setuptools
          pip install buildozer==1.4.0 cython==0.29.19

      - name: Accept SDK licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true

      - name: Update Autoconf Macros
        run: |
          autoupdate || true
          autoreconf -i || true

      - name: Build APK
        run: |
          buildozer android clean
          buildozer -v android debug
        env:
          BUILDOLDER_NO_CACHE: '1'
          ANDROID_SDK_HOME: /usr/lib/android-sdk
          ANDROID_NDK_HOME: /usr/lib/android-ndk

