name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:     

      - name: Upload APK (wildcard)
        uses: actions/upload-artifact@v3
        with:
          name: kwdev-debug-apk
          path: bin/*-debug.apk  # Matches any APK ending with "-debug.apk"


