name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git unzip openjdk-17-jdk python3-pip \
            autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev \
            libffi-dev libssl-dev

      - name: Fix libtool/autoconf
        run: |
          libtoolize --force
          aclocal
          autoheader
          automake --force-missing --add-missing
          autoreconf -ivf

      - name: Install Buildozer
        run: |
          pip install buildozer cython==0.29.19

      - name: Build APK
        run: |
          yes | buildozer --verbose android debug
